apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: ipa
    env: dev
spec:
  project: default
  destination:
    name: in-cluster
    namespace: ipa-dev
  source:
    repoURL: https://github.com/larsschumacher/ipa-apps.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      include: '**/application.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true