apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: ipa
  source:
    repoURL: https://github.com/larsschumacher/ipa-apps.git
    targetRevision: HEAD
    path: /apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true