kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/name: competitive-pricing

labels:
- pairs:
    tags.datadoghq.com/service: competitive-pricing
  includeSelectors: false
  includeTemplates: true

resources:
- deployment.yaml
- service.yaml
