apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa-dev-price-optimisation
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: ipa-dev
  source:
    repoURL: https://github.com/larsschumacher/ipa-apps.git
    path: apps/price-optimisation/envs/dev
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
